- hosts: slave
  become: yes
  tasks:
    - name: Log ind i Docker Hub
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_user }}" --password-stdin

    - name: Stop og fjern eksisterende container
      shell: docker rm -f apache-container || true

    - name: Pull nyeste Apache image
      shell: docker pull mick1746/myapp:latest

    - name: Start Apache container
      shell: docker run -d --name apache-container -p 80:80 mick1746/myapp:latest
